services:

  mongo-express:
    container_name: mongo-express
    restart: unless-stopped
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: vimmlair
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: vimmlair
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - vimmlair-crawler

  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongodb/mongodb-atlas-local
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: vimmlair
    ports:
      - 27017:27017
    volumes:
      - mongo-vimmlair-data:/data/db
    networks:
      - vimmlair-crawler

volumes:
  mongo-vimmlair-data:
    driver: local

networks:
  vimmlair-crawler:
    driver: bridge